branches:
  - master
  - name: next
    channel: next
    prerelease: true
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
        - type: docs
          release: patch
  - - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: docs/CHANGELOG.md
  - - '@semantic-release/exec'
    - publishCmd: echo '::set-env name=CREATE_RELEASE::true'
  - - '@semantic-release/git'
    - assets:
        - package.json
        - yarn.lock
