dist: focal
os: linux
arch:
  - amd64
  - arm64
language: node_js
node_js:
  - 14

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - sudo apt install dpkg fakeroot

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: 'classic'
    - name: http
    - name: lxd
      channel: stable
  apt:
    update: true

script:
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - yarn make
  - snapcraft --use-lxd

after_success:
  - find out -type f -name '*.deb' -exec cp '{}' ozone-display.deb \;

after_failure:
  - sudo journalctl -u snapd

deploy:
  provider: snap
  snap: dist/ozone-display*.snap
  channel: edge
  skip_cleanup: true

  ./config.sh --url https://github.com/Schiller40/ozone --token AGBICSYY4WFNS3VWISVAVSC7HUJWE