dist: focal

arch:
  - amd64
  - arm64

script:
  - yarn package
  - yarn dist

language: node_js
node_js:
  - 14
cache: yarn

before_install:
  - sudo apt install snapd
  - sudo snap install snapcraft --classic
  - sudo snap install multipass --candidate

deploy:
  provider: snap
  snap: dist/ozone-display*.snap
  channel: edge
  skip_cleanup: true
