dist: focal

arch:
  - amd64
  - arm64

script:
  - yarn package
  - yarn dist

language: node_js
node_js:
  - 14
cache: yarn

deploy:
  provider: snap
  snap: dist/ozone-display*.snap
  channel: edge
  skip_cleanup: true
