name: ozone-display
base: core20
summary: Summary
description: |
  Description
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

parts:
  discord:
    after: [dekstop-gtk3]
    plugin: dump
    source: ozone-display.deb
    source-type: deb

    build-packages:
      - curl
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils

  # Adapted from snapcraft-desktop-helpers https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L183
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ['FLAVOR=gtk3']
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0 # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

apps:
  ozone-display:
    command: $SNAP/usr/lib/ozone-display/ozone-display
    command-chain:
      - bin/desktop-launch
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - browser-support
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-observe
      - unity7
