name: ozone-display
base: core18
version: git

summary: Summary
description: |
  Description

confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

assumes:
  - command-chain
  - common-data-dir

apps:
  ozone-display:
    daemon: simple
    restart-condition: always
    command: ./drop-privs.sh bin/desktop-launch bin/xwayland-kiosk-launch $SNAP/ozone-display/ozone-display
    plugs:
      - browser-support
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland
      - network-observe
      - process-control
      - screen-inhibit-control

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

system-usernames:
  snap_daemon: shared

parts:
  drop-privs:
    plugin: dump
    source: build
    override-build: |
      cp ./drop-privs.sh $SNAPCRAFT_PART_INSTALL/drop-privs.sh
      chmod +x  $SNAPCRAFT_PART_INSTALL/drop-privs.sh
    stage-packages:
      - setpriv

  # Adapted from snapcraft-desktop-helpers https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L183
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ['FLAVOR=gtk3']
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0 # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - libgtk2.0-0

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages:
      - build-essential
    stage-packages:
      - xwayland
      - i3
      - libegl1-mesa
      - libgl1-mesa-glx

  ozone-display:
    after: [drop-privs, desktop-gtk3, xwayland-kiosk-helper]
    plugin: dump
    source: .
    source-type: local
    override-build: |
      case $SNAPCRAFT_ARCH_TRIPLET in
          "i386-linux-gnu") ARCH="ia32";;
          "x86_64-linux-gnu") ARCH="x64";;
          "arm-linux-gnueabihf") ARCH="armv7l";;
          "aarch64-linux-gnu") ARCH="arm64";;
          *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
      esac
      curl -s https://nodejs.org/dist/v14.8.0/node-v14.8.0-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install
      npm install -g yarn
      yarn package
      cp -R out/ozone-display-linux-$ARCH $SNAPCRAFT_PART_INSTALL/ozone-display

    build-packages:
      - curl
      - sed
      - unzip

    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
      - libx11-xcb1
      - libxtst6
      - libasound2
      - libnotify4
      - libatspi2.0-0
      - kde-cli-tools
      - kde-runtime
      - trash-cli
      - libglib2.0-bin
      - gvfs-bin
      - setpriv
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - libslang2
