name: ozone-display
version: 1.0.0
summary: Pretty Awesome
description: |
  App description
grade: devel
confinement: devmode
base: core20

apps:
  ozone-display:
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - unity7
      - x11
      - pulseaudio
      - opengl
      - browser-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    command: desktop-launch '$SNAP/ozone-display/ozone-display'
    slots:
      - ozone-display-mpris
parts:
  ozone-display:
    source: out/
    plugin: dump
    stage-packages:
      - libnotify4
      - libnss3
      - libpcre3
      - libxss1
      - libxtst6
      - pulseaudio
      - libgl1-mesa-glx
      - libglu1-mesa
    after: [desktop-gtk3]
    organize:
      ozone-display-linux-x64: ozone-display

    # Adapted from snapcraft-desktop-helpers https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L183
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ['FLAVOR=gtk3']
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0 # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

slots:
  ozone-display-mpris:
    interface: mpris
    name: com.example.mpris
plugs:
  browser-sandbox:
    allow-sandbox: true
    interface: browser-support
