name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-10.15, windows-2019, ubuntu-18.04]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout Changes
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn
      - name: Build library
        run: yarn make
        env:
          CI: true
      # - name: Cleanup artifacts
      #   run: npx rimraf "out/!(*.exe|*.deb|*.AppImage|*.dmg)"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: out/make
      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true
